services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    networks:
      - spring-network

  app:
    image: eclipse-temurin:17-jdk-alpine
    container_name: spring-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasks_db
      SPRING_DATASOURCE_USERNAME: user_tasks
      SPRING_DATASOURCE_PASSWORD: password_tasks
    depends_on:
      - db
    command: ./mvnw spring-boot:run
    networks:
      - spring-network

  db-admin:
    image: adminer
    container_name: db-admin
    ports:
      - "8081:8080"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
