# 1. Configuración de la conexión a la DB
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks_db
spring.datasource.username=user
spring.datasource.password=user

# 2. Driver de Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect